baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

theme = "ananke"

[menu]
  [[menu.main]]
	identifier = "my-first-post"
	name = "my-first-post"
	title = "my-first-post"
	url = "/my-first-post/"
	weight = 0
  [[menu.main]]
	identifier = "posts"
	name = "Posts1"
	title = "Posts12"
	url = "/posts/"
	weight = 0