baseURL = 'https://runtimevic.github.io/HugoDocuTest/'
languageCode = 'en-us'
title = 'My New Hugo Site'

theme = "ananke"

[languages]
  [languages.en]
    title = "Ananke"
    weight = 1
    contentDir = "content/en"
    # languageDirection = 'rtl' for Right-To-Left languages
  [languages.fr]
    title = "Ananke es"
    weight = 2
    contentDir = "content/es"